server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:5432/database_account_service
    username: admin
    password: 12345
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: db/changelog/main-changelog.xml
